/**
 * React Hook which allows throwing an error (catchable via ErrorBoundary) from another hook or promise
 * @see https://github.com/facebook/react/issues/14981
 */
export declare function useThrowError(): (error: Error) => void;
//# sourceMappingURL=useThrowError.d.ts.map